name: Node.js CD

on:
  push:
    branches: [ master ]
jobs:
  example:
    runs-on: ubuntu-latest

    steps:
    - name: Print Secret
      run: echo "My secret value is ${{ secrets.HOST }} user ${{ secrets.USERNAME }} password ${{ secrets.PASSWORD }}"
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /root/cupipon-server
          mkdir /root/tempUploads
          mv uploads/* ../tempUploads/        
          git fetch origin
          git reset --hard HEAD
          git pull origin
          git status
          rm -r uploads
          source /root/.bashrc
          export PATH=$PATH:/root/.nvm/versions/node/v21.4.0/bin/
          npm install
          npm run build
          mkdir /root/cupipon-server/uploads
          mv /root/tempUploads/* /root/cupipon-server/uploads
          rm -r /root/tempUploads
          pm2 restart 0