name: Node.js CD

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          cd /root/cupipon-server
          mv uploads ../cupipon-server-uploads
          git fetch origin
          git reset --hard HEAD
          git pull origin
          git status
          source /root/.bashrc
          export PATH=$PATH:/root/.nvm/versions/node/v16.15.1/bin/
          npm install
          npm run build
          mv /root/cupipon-server-uploads /root/cupipon-server/uploads
          pm2 restart 0